#!/usr/bin/env bash
set -euo pipefail

# Renders the frugal-harness delegation profile from the JSON source of truth
# (~/.config/frugal/profile.json) into a human-readable markdown file that both
# Claude (via CLAUDE.md import) and Codex (via AGENTS.md) consume. It also pins
# per-agent model/effort defaults for the subscribed agents and regenerates the
# Codex standalone harness.

PROFILE="${FRUGAL_PROFILE:-$HOME/.config/frugal/profile.json}"
SHARED_DIR="$HOME/.claude/shared"
PROFILE_MD="$SHARED_DIR/delegation-profile.md"
CODEX_CONFIG="$HOME/.codex/config.toml"
ANTIGRAVITY_SETTINGS="$HOME/.gemini/antigravity-cli/settings.json"
SYNC_SCRIPT="$HOME/.claude/scripts/sync-agents.sh"

if [[ ! -f "$PROFILE" ]]; then
  echo "Missing profile: $PROFILE (run 'frugal config' or install.sh first)" >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "Missing node — required to read $PROFILE" >&2
  exit 1
fi

ensure_json_file() {
  local file="$1"
  mkdir -p "$(dirname "$file")"
  [ -f "$file" ] || printf '{}\n' > "$file"
}

set_toml_root_key() {
  local file="$1" key="$2" value="$3" tmp
  tmp=$(mktemp)
  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0; in_root = 1 }
    in_root && $1 == key && $2 == "=" {
      if (!done) { print key " = \"" value "\""; done = 1 }
      next
    }
    /^\[/ {
      if (!done) { print key " = \"" value "\""; done = 1 }
      in_root = 0
    }
    { print }
    END { if (!done) print key " = \"" value "\"" }
  ' "$file" > "$tmp" && mv "$tmp" "$file"
}

set_antigravity_settings() {
  local file="$1"
  ensure_json_file "$file"
  node -e '
const fs = require("fs");
const [file] = process.argv.slice(1);
let data = {};
try { data = JSON.parse(fs.readFileSync(file, "utf8")); } catch {}
data.model = "Claude Sonnet 4.6 (Thinking)";
fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
' "$file"
}

mkdir -p "$SHARED_DIR"

# 1. Render delegation-profile.md from profile.json
node -e '
const fs = require("fs");
const [profilePath, outPath] = process.argv.slice(1);
const p = JSON.parse(fs.readFileSync(profilePath, "utf8"));
const NAME = { claude: "Claude", antigravity: "Antigravity", codex: "Codex" };
const name = (k) => NAME[k] || k;
const agents = (p.agents || []).map(name);
const roles = p.roles || {};
const order = [
  ["plan", "Plan"],
  ["exec", "Implementation (exec)"],
  ["review", "Review"],
  ["docs", "Docs"],
  ["ship", "Ship (commit/push)"],
];
const lines = [];
lines.push("# Delegation Profile");
lines.push("# AUTO-GENERATED by render-profile.sh from ~/.config/frugal/profile.json");
lines.push("# Do not edit directly. Re-run `frugal config` to change it.");
lines.push("");
lines.push(`Subscribed worker agents: ${agents.length ? agents.join(", ") : "(none)"}.`);
lines.push("");
if ((p.routing || "complexity-auto") === "complexity-auto") {
  lines.push("Routing: complexity-auto. Apply the shared Model Auto-Routing Criteria in harness-core.md:");
  lines.push("- Standard tasks: plan on Sonnet; Codex effort `medium`; Antigravity model `Claude Sonnet 4.6 (Thinking)`.");
  lines.push("- Complex tasks: plan on Opus (after user approval); Codex effort `xhigh`; Antigravity model `Claude Opus 4.6 (Thinking)`.");
} else {
  lines.push(`Routing: ${p.routing}.`);
}
lines.push("");
lines.push("Per-role delegation priority (try the first agent; fall back down the list if it is unavailable or out of quota):");
for (const [key, label] of order) {
  const list = (roles[key] || []).map(name);
  lines.push(`- ${label}: ${list.length ? list.join(" -> ") : "(unset)"}`);
}
lines.push("");
lines.push("Antigravity model fallback chain (use in order; switch when the current model is out of quota or unavailable):");
lines.push("  1. `Claude Sonnet 4.6 (Thinking)` — default for standard tasks");
lines.push("  2. `Claude Opus 4.6 (Thinking)` — default for complex tasks");
lines.push("  3. `Gemini 3.1 Pro (High)` — fallback when Claude quota exhausted");
lines.push("  4. `Gemini 3.5 Flash (Medium)` — last resort");
lines.push("");
lines.push("Invocation forms:");
lines.push("- Antigravity standard: `agy --model \"Claude Sonnet 4.6 (Thinking)\" -p \"<task>\"`");
lines.push("- Antigravity complex:  `agy --model \"Claude Opus 4.6 (Thinking)\" -p \"<task>\"`");
lines.push("- Antigravity (add `--dangerously-skip-permissions` when the task requires autonomous file edits).");
lines.push("- Codex standard: `codex exec \"<task>\" < /dev/null`.");
lines.push("- Codex complex:  `codex -c plan_mode_reasoning_effort=xhigh exec \"<task>\" < /dev/null`.");
lines.push("");
fs.writeFileSync(outPath, lines.join("\n") + "\n");
' "$PROFILE" "$PROFILE_MD"

# 2. Read subscribed agents
AGENTS=$(node -e 'const p=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"));process.stdout.write((p.agents||[]).join(" "))' "$PROFILE")

# 3. Pin per-agent defaults for subscribed agents only
for a in $AGENTS; do
  case "$a" in
    codex)
      mkdir -p "$(dirname "$CODEX_CONFIG")"
      [ -f "$CODEX_CONFIG" ] || : > "$CODEX_CONFIG"
      set_toml_root_key "$CODEX_CONFIG" "model" "gpt-5.5"
      set_toml_root_key "$CODEX_CONFIG" "model_reasoning_effort" "medium"
      set_toml_root_key "$CODEX_CONFIG" "plan_mode_reasoning_effort" "medium"
      ;;
    antigravity)
      set_antigravity_settings "$ANTIGRAVITY_SETTINGS"
      ;;
  esac
done

# 4. Regenerate Codex standalone harness so it carries the same priorities
if [ -x "$SYNC_SCRIPT" ]; then
  "$SYNC_SCRIPT" >/dev/null
fi

echo "Wrote $PROFILE_MD"
