#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="$HOME/.frugal-harness/config.sh"
if [ -f "$CONFIG_FILE" ]; then
  source "$CONFIG_FILE"
else
  FRUGAL_MAIN="claude"
  FRUGAL_HELPERS="codex,agy"
  FRUGAL_DEPLOY_CLAUDE="yes"
fi

CORE="$HOME/.claude/shared/harness-core.md"
OUT_CODEX="$HOME/.codex/AGENTS.md"
OUT_AGY="$HOME/.gemini/config/AGENTS.md"
OUT_CLAUDE="$HOME/.claude/CLAUDE.md"

if [[ ! -f "$CORE" ]]; then
  echo "Missing core: $CORE" >&2
  exit 1
fi

timestamp="$(date '+%Y-%m-%dT%H:%M:%S%z')"

generate_agent_md() {
  local agent_name="$1"
  local is_main="$2"
  local out_file="$3"
  
  local wrapper_file
  if [ "$is_main" = "1" ]; then
    wrapper_file="$HOME/.claude/shared/${agent_name}-wrapper-main.md"
  else
    wrapper_file="$HOME/.claude/shared/${agent_name}-wrapper-helper.md"
  fi

  if [[ -f "$wrapper_file" ]]; then
    mkdir -p "$(dirname "$out_file")"
    {
      if [ "$is_main" = "1" ]; then
        echo "# frugal-harness - $agent_name (Main Handler)"
      else
        echo "# frugal-harness - $agent_name (Helper / Executor)"
      fi
      echo "# AUTO-GENERATED by $(basename "$0") on $timestamp"
      echo "# Do not edit directly. Edit harness-core.md or ${agent_name}-wrapper-*.md."
      echo
      cat "$CORE"
      echo
      echo "---"
      echo
      cat "$wrapper_file"
    } > "$out_file"
    echo "Wrote $out_file ($(wc -l < "$out_file") lines) [Main: $is_main]"
  fi
}

# 1. Generate Codex AGENTS.md
if [ "$FRUGAL_MAIN" = "codex" ]; then
  generate_agent_md "codex" "1" "$OUT_CODEX"
elif [[ "$FRUGAL_HELPERS" == *"codex"* ]]; then
  generate_agent_md "codex" "0" "$OUT_CODEX"
else
  # Remove if not main and not a helper
  rm -f "$OUT_CODEX"
fi

# 2. Generate agy AGENTS.md
if [ "$FRUGAL_MAIN" = "agy" ]; then
  generate_agent_md "agy" "1" "$OUT_AGY"
elif [[ "$FRUGAL_HELPERS" == *"agy"* ]]; then
  generate_agent_md "agy" "0" "$OUT_AGY"
else
  rm -f "$OUT_AGY"
fi

# 3. Deploy CLAUDE.md
if [ "$FRUGAL_MAIN" = "claude" ] || [ "$FRUGAL_DEPLOY_CLAUDE" = "yes" ]; then
  # CLAUDE.md doesn't have a main/helper split because it's always an orchestrator.
  # But we might need to copy it from the repo. 
  # Actually sync-agents.sh is usually run from the repo or it assumes CLAUDE.md is downloaded.
  # The installer downloads CLAUDE.md to ~/.claude/CLAUDE.md.
  # So we don't necessarily generate it here, we just leave it.
  echo "CLAUDE.md deployment enabled."
else
  rm -f "$OUT_CLAUDE"
  echo "Removed $OUT_CLAUDE (not main handler and deploy disabled)."
fi
