#!/usr/bin/env bash
set -euo pipefail

CORE="$HOME/.claude/shared/harness-core.md"
WRAPPER="$HOME/.claude/shared/codex-wrapper.md"
OUT="$HOME/.codex/AGENTS.md"

if [[ ! -f "$CORE" ]]; then
  echo "Missing core: $CORE" >&2
  exit 1
fi

if [[ ! -f "$WRAPPER" ]]; then
  echo "Missing wrapper template: $WRAPPER" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
timestamp="$(date '+%Y-%m-%dT%H:%M:%S%z')"

{
  echo "# frugal-harness - Codex (executor + fallback orchestrator)"
  echo "# AUTO-GENERATED by $(basename "$0") on $timestamp"
  echo "# Do not edit directly. Edit harness-core.md or codex-wrapper.md."
  echo
  cat "$CORE"
  echo
  echo "---"
  echo
  cat "$WRAPPER"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
