#!/usr/bin/env bash
set -euo pipefail

CORE="$HOME/.claude/shared/harness-core.md"
WRAPPER_CODEX="$HOME/.claude/shared/codex-wrapper.md"
WRAPPER_AGY="$HOME/.claude/shared/agy-wrapper.md"
OUT_CODEX="$HOME/.codex/AGENTS.md"
OUT_AGY="$HOME/.gemini/config/AGENTS.md"

if [[ ! -f "$CORE" ]]; then
  echo "Missing core: $CORE" >&2
  exit 1
fi

timestamp="$(date '+%Y-%m-%dT%H:%M:%S%z')"

if [[ -f "$WRAPPER_CODEX" ]]; then
  mkdir -p "$(dirname "$OUT_CODEX")"
  {
    echo "# frugal-harness - Codex (executor + fallback orchestrator)"
    echo "# AUTO-GENERATED by $(basename "$0") on $timestamp"
    echo "# Do not edit directly. Edit harness-core.md or codex-wrapper.md."
    echo
    cat "$CORE"
    echo
    echo "---"
    echo
    cat "$WRAPPER_CODEX"
  } > "$OUT_CODEX"
  echo "Wrote $OUT_CODEX ($(wc -l < "$OUT_CODEX") lines)"
fi

if [[ -f "$WRAPPER_AGY" ]]; then
  mkdir -p "$(dirname "$OUT_AGY")"
  {
    echo "# frugal-harness - agy (executor + fallback orchestrator)"
    echo "# AUTO-GENERATED by $(basename "$0") on $timestamp"
    echo "# Do not edit directly. Edit harness-core.md or agy-wrapper.md."
    echo
    cat "$CORE"
    echo
    echo "---"
    echo
    cat "$WRAPPER_AGY"
  } > "$OUT_AGY"
  echo "Wrote $OUT_AGY ($(wc -l < "$OUT_AGY") lines)"
fi
